/**
 * Navratri Event Management Platform - Constants & Global Enums
 */
const NAVRATRI_CONSTANTS = {
  STORAGE_KEY_DB: "NAVRATRI_DB_V1",
  STORAGE_KEY_SESSION: "NAVRATRI_SESSION_V1",
  TOTAL_VENUE_CAPACITY: 1200,
  ROLES: {
    SUPER_ADMIN: "super_admin",
    ADMIN: "admin",
    GATE_SCANNER: "gate_scanner",
    VISITOR: "visitor"
  },
  PERMISSIONS: {
    ALL_ACCESS: "ALL_ACCESS",
    VIEW_ANALYTICS: "VIEW_ANALYTICS",
    VERIFY_PAYMENTS: "VERIFY_PAYMENTS",
    GATE_SCANNER: "GATE_SCANNER",
    SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
    VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
    BOOK_PASS: "BOOK_PASS",
    VIEW_GALLERY: "VIEW_GALLERY"
  }
};

Object.freeze(NAVRATRI_CONSTANTS);
